#!/usr/bin/env python3
"""flow_fixture_compiler.py — task 3.1: project a `kind: conversation` scenario
IR document (schema/scenario_ir.schema.json, compiled by scenario_compiler.py)
onto a runnable `kitsoki test flows` flow fixture + host cassette pair.

## Why not `internal/testrunner/fromtrace.go`'s shape directly

`trace to-flow` (cmd/kitsoki/trace.go, internal/testrunner/fromtrace.go)
converts a recorded kitsoki ENGINE trace, where every turn already carries a
resolved `intent: {name, slots}` (a real router decision). A mined scenario
IR turn only has free-text `turns[].text` — there is no resolved intent/slots
upstream, and resolving each mined utterance against some arbitrary story's
real intents is a much bigger, story-specific problem this compiler does not
attempt (see docs/proposals/scenario-foundry.md's flow-fixture compiler note).

Instead this compiler targets ONE fixed, purpose-built harness app —
`stories/scenario-foundry-harness/` — that exposes a single explicit `ask`
intent (`slots.text`) which hands the verbatim utterance to a stubbed
`host.agent.converse` and stays put. This mirrors stories/off-ramp-demo's
free-text-answered-in-place mechanic, but uses an explicit intent instead of
a clarify/off-ramp no-match: internal/testrunner's orchestrator-backed runner
(required for `host_cassette:`) does not support recording-resolved `input:`
turns today (see internal/testrunner/flows.go's runOneFlowOrchestrator —
"recording routing not yet supported on orchestrator path"). Explicit
`intent:` turns sidestep that gap entirely and are fully supported combined
with `host_cassette:`.

## Shape emitted

- One flow turn per mined `turns[]` entry: `intent: {name: ask, slots: {text:
  <verbatim>}}`, `display_input: <verbatim>` (mirrors fromtrace.go's own
  display_input convention — the trace/replay UI shows the operator's real
  words even though a fixed intent drives routing).
- One host_cassette episode per turn, matched on `handler: host.agent.converse`
  (sequential, non-replay:any — matches the i-th call to the i-th episode,
  exactly like fromtrace.go's converter), whose canned `answer` is derived
  deterministically from the scenario's own fields (corrective_ops on a
  corrected turn; expected_effects on the scenario's final turn; a generic
  acknowledgement otherwise) — never invented content, never a live call.

## Determinism

Pure function of the scenario IR document's bytes: same input, same output
bytes (byte-for-byte), so the compiled fixture set is itself a regression
artifact a reviewer can regenerate and diff (mirrors scenario_compiler.py's
own determinism contract).

Usage:
  python3 flow_fixture_compiler.py --scenarios-dir calibration --out calibration/flows
  python3 flow_fixture_compiler.py --scenario calibration/scn-foo-0000.json --out /tmp/out
"""
import argparse
import glob
import json
import os
import sys

HARNESS_APP_REL = "stories/scenario-foundry-harness/app.yaml"

FLOW_HEADER = (
    "# Generated by tools/session-mining/flow_fixture_compiler.py (task 3.1).\n"
    "# DO NOT EDIT BY HAND — regenerate from the source scenario IR document.\n"
    "# Turns are one-per-mined-user-turn, each projected onto the fixed `ask`\n"
    "# intent of stories/scenario-foundry-harness (slots.text drives the\n"
    "# stubbed host.agent.converse call; display_input carries the operator's\n"
    "# verbatim words for the trace/replay UI). See the module docstring for\n"
    "# why this app rather than the source story's own intents.\n"
)

CASSETTE_HEADER = (
    "# Generated by tools/session-mining/flow_fixture_compiler.py (task 3.1).\n"
    "# DO NOT EDIT BY HAND — regenerate from the source scenario IR document.\n"
    "# One episode per mined turn, matched on handler (sequential — the i-th\n"
    "# converse call consumes the i-th episode). Canned answers are derived\n"
    "# deterministically from the scenario's own corrective_ops/expected_effects\n"
    "# fields, never invented content.\n"
)


def _yaml_str(s):
    """Render a Python string as a YAML double-quoted scalar (valid on any
    single-line string; mined turn text has already been through prep.py's
    whitespace-collapsing distillation, so embedded newlines are not expected,
    but we escape defensively via json.dumps, which produces valid YAML
    double-quoted-scalar syntax for any string)."""
    return json.dumps(s)


def canned_answer(scenario, turn_index):
    """Deterministically derive the canned converse answer for turn_index
    (0-based) in scenario. Never invents content: only reflects fields
    already present on the (redacted) scenario IR document.
    """
    turn = scenario["turns"][turn_index]
    is_last = turn_index == len(scenario["turns"]) - 1
    if turn.get("corrected") and turn.get("corrective_ops"):
        ops = "; ".join(turn["corrective_ops"])
        return "noted — a correction followed (%s)" % ops
    if is_last and scenario.get("expected_effects"):
        effects = "; ".join(scenario["expected_effects"])
        return "acknowledged — expected effects: %s" % effects
    if scenario.get("abandoned") and is_last:
        return "acknowledged (scenario ends unresolved in the source session)"
    return "acknowledged"


def compile_scenario(scenario):
    """Compile one scenario IR document (already-parsed dict) into
    (flow_yaml_bytes, cassette_yaml_bytes). Pure function of `scenario`.
    """
    if scenario.get("kind") != "conversation":
        raise ValueError("flow_fixture_compiler: not a kind:conversation document: %r" % scenario.get("kind"))
    turns = scenario.get("turns") or []
    if not turns:
        raise ValueError("flow_fixture_compiler: scenario %s has no turns" % scenario.get("id"))

    scenario_id = scenario["id"]
    cassette_name = "%s.cassette.yaml" % scenario_id

    flow_lines = [
        FLOW_HEADER,
        "test_kind: flow",
        "app: ../../../../stories/scenario-foundry-harness/app.yaml",
        "host_cassette: %s" % cassette_name,
        "initial_state: desk",
        "initial_world: {}",
        "turns:",
    ]
    cassette_lines = [
        CASSETTE_HEADER,
        "kind: host_cassette",
        "app_id: scenario-foundry-harness",
        'app_version: "0.1.0"',
        "match_on: [handler]",
        "",
        "episodes:",
    ]

    for i, turn in enumerate(turns):
        text = turn["text"]
        flow_lines.append("  - intent: { name: ask, slots: { text: %s } }" % _yaml_str(text))
        flow_lines.append("    display_input: %s" % _yaml_str(text))
        flow_lines.append("    expect_state: desk")
        answer = canned_answer(scenario, i)
        flow_lines.append("    expect_world: { last_answer: %s }" % _yaml_str(answer))

        cassette_lines.append("  - id: converse_%d" % (i + 1))
        cassette_lines.append("    match: { handler: host.agent.converse }")
        cassette_lines.append("    response:")
        cassette_lines.append("      data:")
        cassette_lines.append("        answer: %s" % _yaml_str(answer))

    flow_lines.append("expect_no_errors: true")

    flow_yaml = "\n".join(flow_lines) + "\n"
    cassette_yaml = "\n".join(cassette_lines) + "\n"
    return flow_yaml.encode("utf-8"), cassette_yaml.encode("utf-8")


def load_scenarios(paths):
    docs = []
    for p in paths:
        with open(p, "r", encoding="utf-8") as f:
            docs.append(json.load(f))
    return docs


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--scenarios-dir", help="directory of scn-*.json scenario IR documents")
    ap.add_argument("--scenario", action="append", default=[], help="a single scenario IR file (repeatable)")
    ap.add_argument("--out", required=True, help="output directory for compiled .flow.yaml/.cassette.yaml pairs")
    args = ap.parse_args(argv)

    paths = list(args.scenario)
    if args.scenarios_dir:
        paths.extend(sorted(glob.glob(os.path.join(args.scenarios_dir, "scn-*.json"))))
    if not paths:
        print("flow_fixture_compiler: no scenario IR documents given (use --scenarios-dir or --scenario)", file=sys.stderr)
        return 2

    os.makedirs(args.out, exist_ok=True)
    compiled = 0
    for scenario in load_scenarios(paths):
        flow_yaml, cassette_yaml = compile_scenario(scenario)
        scenario_id = scenario["id"]
        flow_path = os.path.join(args.out, "%s.flow.yaml" % scenario_id)
        cassette_path = os.path.join(args.out, "%s.cassette.yaml" % scenario_id)
        with open(flow_path, "wb") as f:
            f.write(flow_yaml)
        with open(cassette_path, "wb") as f:
            f.write(cassette_yaml)
        compiled += 1
    print("flow_fixture_compiler: compiled %d scenario(s) into %s" % (compiled, args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
