"""Deterministic Slidey deck generation for Persona QA run bundles."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


DECK_RESOLUTION = {"width": 1920, "height": 1080}


def build_deck(
    run_dir: Path,
    *,
    title: str = "",
    max_playback_scenes: int = 6,
    source_ref: str = "",
) -> dict[str, Any]:
    """Build a stable Slidey spec from a Persona QA / product-journey run dir.

    The renderer is deliberately offline: it only reads JSON artifacts already
    present in ``run_dir`` and never records media or invokes a model. Re-running
    it over the same files produces byte-identical JSON when written with
    :func:`deck_json`.
    """

    run = _read_json(run_dir / "run.json")
    media_manifest = _read_optional_json(run_dir / "media-manifest.json", {"items": [], "summary": {}})
    outcomes = _read_optional_json(run_dir / "scenario-outcomes.json", {"items": [], "summary": {}})
    findings = _read_optional_json(run_dir / "findings.json", {"items": [], "summary": {}})
    review = _read_optional_json(run_dir / "review.json", {"status": "not_reviewed", "summary": "", "checks": []})
    metrics = _read_optional_json(run_dir / "metrics.json", {})
    driver_plan = _read_optional_json(run_dir / "driver-plan.json", {"scenarios": []})
    driver_journal = _read_optional_json(run_dir / "driver-journal.json", {"items": []})

    run_id = str(run.get("run_id", run_dir.name))
    project = _as_dict(run.get("project"))
    persona = _as_dict(run.get("persona"))
    project_label = _label(project, "Project")
    persona_label = _label(persona, "Persona")
    deck_title = title or f"{project_label} Persona QA"
    scenarios = [_as_dict(item) for item in run.get("scenarios", [])]
    playback_items = _playback_items(media_manifest)
    playback_scenes = _playback_scenes(playback_items, max_playback_scenes=max_playback_scenes)

    scenes: list[dict[str, Any]] = [
        {
            "type": "title",
            "eyebrow": "Persona QA",
            "title": deck_title,
            "subtitle": f"{project_label} - {persona_label} - {run_id}",
            "narration": "This deck was generated deterministically from an existing Persona QA run bundle and its recorded media manifest.",
            "hold": 2600,
        },
        _persona_scene(persona),
        _scenario_table_scene(scenarios, outcomes, media_manifest),
        _review_scene(review, metrics),
        _findings_scene(findings, outcomes),
        _media_manifest_scene(playback_items, media_manifest),
    ]

    driver_scene = _driver_scene(driver_plan, driver_journal)
    if driver_scene is not None:
        scenes.append(driver_scene)
    scenes.extend(playback_scenes)
    display_run_dir = source_ref or run_dir.name
    scenes.append(_next_scene(display_run_dir, playback_scenes))

    return {
        "_comment": f"Generated by kitsoki persona-qa deck from {display_run_dir} ({run_id}). Re-run the command instead of hand-editing derived scenes.",
        "meta": {
            "mode": "pitch",
            "title": deck_title,
            "resolution": DECK_RESOLUTION,
            "theme": "rose-pine-moon",
        },
        "scenes": scenes,
    }


def write_deck(deck: dict[str, Any], out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(deck_json(deck), encoding="utf-8")


def deck_json(deck: dict[str, Any]) -> str:
    return json.dumps(deck, indent=2, sort_keys=True) + "\n"


def _read_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def _read_optional_json(path: Path, fallback: dict[str, Any]) -> dict[str, Any]:
    if not path.exists():
        return fallback
    return _read_json(path)


def _as_dict(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _as_list(value: Any) -> list[Any]:
    return value if isinstance(value, list) else []


def _label(value: dict[str, Any], fallback: str) -> str:
    return str(value.get("label") or value.get("id") or fallback)


def _first_text(value: Any, fallback: str = "") -> str:
    if isinstance(value, list):
        for item in value:
            text = _first_text(item)
            if text:
                return text
        return fallback
    if isinstance(value, dict):
        return str(value.get("text") or value.get("summary") or value.get("detail") or fallback)
    if value is None:
        return fallback
    return str(value)


def _lines(items: list[str], fallback: str, *, limit: int = 12) -> str:
    cleaned = [item.strip() for item in items if item and item.strip()]
    if not cleaned:
        return fallback
    return "\n".join(cleaned[:limit])


def _persona_scene(persona: dict[str, Any]) -> dict[str, Any]:
    lens = _as_dict(persona.get("persona_lens"))
    risk_focus = ", ".join(str(item) for item in _as_list(persona.get("risk_focus")))
    body = _lines(
        [
            f"Description: {persona.get('description', '')}",
            f"Surface preference: {persona.get('surface_preference', '')}",
            f"Risk focus: {risk_focus}",
            f"Starting surface: {lens.get('starting_surface', '')}",
            f"First question: {lens.get('first_question', '')}",
            f"Evidence emphasis: {lens.get('evidence_emphasis', '')}",
            f"Escalation trigger: {lens.get('escalation_trigger', '')}",
            f"Finding bias: {lens.get('finding_bias', '')}",
        ],
        "No persona lens was recorded.",
    )
    return {
        "type": "narrative",
        "eyebrow": "Persona lens",
        "lede": _label(persona, "Persona"),
        "body": body,
        "narration": "The deck keeps the persona lens visible so reviewers judge the scenario evidence from the intended point of view.",
        "hold": 6200,
    }


def _scenario_table_scene(scenarios: list[dict[str, Any]], outcomes: dict[str, Any], media_manifest: dict[str, Any]) -> dict[str, Any]:
    outcomes_by_id = {
        str(item.get("scenario", "")): _as_dict(item)
        for item in _as_list(outcomes.get("items"))
        if isinstance(item, dict)
    }
    playback_by_scenario: dict[str, int] = {}
    for item in _playback_items(media_manifest):
        scenario = str(item.get("scenario", ""))
        playback_by_scenario[scenario] = playback_by_scenario.get(scenario, 0) + 1
    rows = []
    for scenario in sorted(scenarios, key=lambda item: str(item.get("id", ""))):
        scenario_id = str(scenario.get("id", ""))
        outcome = outcomes_by_id.get(scenario_id, {})
        present = outcome.get("present_evidence_count", "")
        required = outcome.get("required_evidence_count", "")
        evidence_ratio = f"{present}/{required}" if present != "" and required != "" else str(scenario.get("evidence_status", "planned"))
        rows.append(
            {
                "cells": [
                    scenario_id,
                    str(scenario.get("stage", "")),
                    str(outcome.get("outcome") or scenario.get("status") or "planned"),
                    evidence_ratio,
                    str(playback_by_scenario.get(scenario_id, 0)),
                ]
            }
        )
    if not rows:
        rows.append({"cells": ["none", "", "not_started", "0/0", "0"]})
    return {
        "type": "table",
        "variant": "scorecard",
        "title": "Recorded scenarios",
        "columns": ["Scenario", "Stage", "Outcome", "Evidence", "Playback"],
        "rows": rows[:10],
        "caption": "Rows are sorted by scenario id for deterministic output.",
        "narration": "The scenario table ties each natural-use task to its outcome, evidence coverage, and playback count.",
        "hold": 7600,
    }


def _review_scene(review: dict[str, Any], metrics: dict[str, Any]) -> dict[str, Any]:
    checks = sorted(
        [item for item in _as_list(review.get("checks")) if isinstance(item, dict)],
        key=lambda item: (str(item.get("status", "")), str(item.get("id", ""))),
    )
    check_lines = [
        f"{item.get('status', 'unknown')}: {item.get('id', 'check')} - {item.get('summary', '')}"
        for item in checks[:8]
    ]
    body = _lines(
        [
            f"Status: {review.get('status', 'not_reviewed')}",
            f"Summary: {review.get('summary', '')}",
            f"Scenarios: {metrics.get('scenario_count', '')}",
            f"Evidence present: {metrics.get('present_evidence_count', '')}/{metrics.get('required_evidence_count', '')}",
            f"Proof evidence: {metrics.get('proof_evidence_count', '')}",
            *check_lines,
        ],
        "No review gate artifact was recorded.",
    )
    return {
        "type": "narrative",
        "eyebrow": "Review gate",
        "lede": str(review.get("status") or "not_reviewed"),
        "body": body,
        "narration": "The review scene summarizes bundle readiness without rerunning capture or model work.",
        "hold": 6600,
    }


def _findings_scene(findings: dict[str, Any], outcomes: dict[str, Any]) -> dict[str, Any]:
    cards = []
    summary = _as_dict(findings.get("summary"))
    if summary:
        cards.extend(
            {
                "label": kind,
                "sub": str(summary.get(kind, 0)),
                "lines": [f"{kind} findings recorded"],
                "style": "primary" if kind in {"strength", "fix"} else "secondary",
            }
            for kind in ["strength", "weakness", "issue", "fix", "blocked"]
        )
    else:
        counts: dict[str, int] = {}
        for item in _as_list(findings.get("items")):
            if isinstance(item, dict):
                kind = str(item.get("kind", "finding"))
                counts[kind] = counts.get(kind, 0) + 1
        cards.extend(
            {
                "label": kind,
                "sub": str(count),
                "lines": [f"{kind} findings recorded"],
                "style": "primary" if kind in {"strength", "fix"} else "secondary",
            }
            for kind, count in sorted(counts.items())
        )
    if not cards:
        cards = [{"label": "findings", "sub": "0", "lines": ["No findings were recorded."], "style": "secondary"}]

    outcome_lines = [
        f"{item.get('scenario', '')}: {item.get('outcome', '')}"
        for item in _as_list(outcomes.get("items"))
        if isinstance(item, dict)
    ]
    return {
        "type": "cards",
        "variant": "grid",
        "title": "Persona judgement",
        "cards": cards[:6],
        "caption": _lines(outcome_lines, "No scenario outcome matrix was recorded.", limit=6),
        "narration": "Findings are grouped by type so a technical reviewer can separate strengths from product risks.",
        "hold": 7400,
    }


def _media_manifest_scene(playback_items: list[dict[str, Any]], media_manifest: dict[str, Any]) -> dict[str, Any]:
    summary = _as_dict(media_manifest.get("summary"))
    caption = _lines(
        [
            f"Playback items: {summary.get('playback_items', len(playback_items))}",
            f"Videos: {summary.get('video', sum(1 for item in playback_items if item.get('media_kind') == 'video'))}",
            f"Images: {summary.get('image', sum(1 for item in playback_items if item.get('media_kind') == 'image'))}",
            "Scenarios: " + ", ".join(sorted({str(item.get("scenario", "")) for item in playback_items if item.get("scenario")})),
        ],
        "No playback media has been attached yet.",
    )
    return {
        "type": "evidence",
        "title": "Playback manifest",
        "items": [
            {
                "label": str(item.get("scenario", "media")),
                "status": _slidey_status(str(item.get("status", "validated"))),
                "detail": str(item.get("notes") or item.get("path", "")),
                "refType": "artifact",
                "ref": str(item.get("path", "")),
            }
            for item in playback_items[:6]
        ]
        or [
            {
                "label": "playback",
                "status": "blocked",
                "detail": "No video, rrweb, or image playback item is present in media-manifest.json.",
                "refType": "path",
                "ref": "media-manifest.json",
            }
        ],
        "caption": caption,
        "narration": "The media scene carries structured playback references so Slidey can render the recorded journey clips.",
        "hold": 8200,
    }


def _driver_scene(driver_plan: dict[str, Any], driver_journal: dict[str, Any]) -> dict[str, Any] | None:
    scenarios = [item for item in _as_list(driver_plan.get("scenarios")) if isinstance(item, dict)]
    events = [item for item in _as_list(driver_journal.get("items")) if isinstance(item, dict)]
    if not scenarios and not events:
        return None
    body = _lines(
        [
            *[
                f"{item.get('scenario', '')}: {item.get('harness', '')} / {item.get('visual_surface', '')}"
                for item in scenarios[:6]
            ],
            *[
                f"event {item.get('event_id', item.get('id', 'driver'))}: {item.get('summary', item.get('action', ''))}"
                for item in events[:6]
            ],
        ],
        "No driver plan or journal event was recorded.",
    )
    return {
        "type": "narrative",
        "eyebrow": "Driver contract",
        "lede": "How the run was captured",
        "body": body,
        "narration": "The driver scene records the capture harness and journal trail behind the visible playback evidence.",
        "hold": 6800,
    }


def _playback_items(media_manifest: dict[str, Any]) -> list[dict[str, Any]]:
    items = []
    for item in _as_list(media_manifest.get("items")):
        if not isinstance(item, dict):
            continue
        path = str(item.get("path", ""))
        if not path:
            continue
        media_kind = str(item.get("media_kind", ""))
        if item.get("playback") or media_kind in {"video", "image"} or path.endswith(".rrweb.json"):
            items.append(item)
    return sorted(
        items,
        key=lambda item: (
            str(item.get("scenario", "")),
            str(item.get("evidence_kind", "")),
            str(item.get("path", "")),
        ),
    )


def _playback_scenes(playback_items: list[dict[str, Any]], *, max_playback_scenes: int) -> list[dict[str, Any]]:
    scenes = []
    for item in playback_items[:max_playback_scenes]:
        scene = _playback_scene(item)
        if scene is not None:
            scenes.append(scene)
    return scenes


def _playback_scene(item: dict[str, Any]) -> dict[str, Any] | None:
    path = str(item.get("path", ""))
    if not path:
        return None
    title = " / ".join(part for part in [str(item.get("scenario", "")), str(item.get("evidence_kind", ""))] if part)
    if not title:
        title = Path(path).name
    media_kind = str(item.get("media_kind", ""))
    caption = str(item.get("notes") or path)
    if media_kind == "image":
        return {
            "type": "image",
            "title": title,
            "src": path,
            "fit": "contain",
            "caption": caption,
            "narration": f"Screenshot evidence for {title}.",
        }
    scene = {
        "type": "video",
        "mode": "embedded",
        "eyebrow": "Playback evidence",
        "title": title,
        "chapters": "auto",
        "caption": caption,
        "narration": f"Recorded playback evidence for {title}.",
    }
    if path.endswith(".rrweb.json"):
        scene["rrweb"] = path
    else:
        scene["src"] = path
    return scene


def _slidey_status(status: str) -> str:
    if status in {"validated", "implemented", "done", "issue", "blocked", "next", "progress", "pending", "skipped"}:
        return status
    if status in {"captured", "fixed", "pass"}:
        return "validated"
    if status in {"missing", "planned", "not_started"}:
        return "pending"
    return "done"


def _next_scene(run_dir: str, playback_scenes: list[dict[str, Any]]) -> dict[str, Any]:
    body = _lines(
        [
            f"Run bundle: {run_dir}",
            f"Playback scenes: {len(playback_scenes)}",
            "Regenerate: kitsoki persona-qa deck --run-dir <run-dir> --out <deck.slidey.json>",
            "Publish: commit the deck JSON; bundle it for the product-site gallery when it lives under docs/decks/.",
        ],
        "Regenerate this deck from the run bundle instead of editing generated scenes by hand.",
    )
    return {
        "type": "narrative",
        "eyebrow": "Next",
        "lede": "Regenerate from source artifacts",
        "body": body,
        "narration": "The deck is a derived artifact. The durable source is the run bundle plus the recorded media manifest.",
        "hold": 5800,
    }
