package queue

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

// Regression coverage for the worst failure mode the protected finalizer can
// produce: a landing that SUCCEEDS and then leaves the protected checkout
// holding a staged reversal of the very commit it just landed, so that a plain
// `git commit` in that checkout silently backs the landed work out.
//
// The production trigger is a permanently dirty path under one of
// PreserveWIP's wipExcludedRoots — in the real protected checkout, the
// regenerated .kitsoki/bin/claude and .kitsoki/bin/codex launch-policy shims,
// which are tracked, always modified, and never committed. PreserveWIP
// deliberately excludes those roots from both capture and cleanup, so they are
// still dirty when syncProtectedCheckout runs. The old sync gated itself on
// `git diff-index --quiet <oldSHA> --` across the WHOLE tree with none of
// wipPathspec's exclusions, so that gate could never pass, the sync was
// refused on every single landing, and the ref moved while the index and
// worktree stayed on the pre-landing tree.
//
// Every fixture in this file therefore carries that dirt. A fixture whose
// protected checkout is conveniently clean proves nothing about this bug: the
// clean case is exactly the case that always worked.

// psrCommitShims adds tracked launch-policy shims under the .kitsoki excluded
// root and commits them, so a later modification is a *tracked* modification
// (which is what the real checkout carries) rather than an untracked file.
func psrCommitShims(t *testing.T, root string) {
	t.Helper()
	for _, name := range []string{"claude", "codex"} {
		p := filepath.Join(root, ".kitsoki", "bin", name)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte("#!/bin/sh\n# shim: committed revision\n"), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	git(t, root, "add", "-f", ".kitsoki/bin/claude", ".kitsoki/bin/codex")
	git(t, root, "commit", "-m", "launch-policy shims")
}

// psrDirtyShims regenerates the shims in the worktree without committing them —
// the permanent, never-clean state of the real protected checkout.
func psrDirtyShims(t *testing.T, root string) {
	t.Helper()
	for _, name := range []string{"claude", "codex"} {
		p := filepath.Join(root, ".kitsoki", "bin", name)
		if err := os.WriteFile(p, []byte("#!/bin/sh\n# shim: regenerated by tooling, never committed\n"), 0o755); err != nil {
			t.Fatal(err)
		}
	}
}

const psrRegeneratedShim = "#!/bin/sh\n# shim: regenerated by tooling, never committed\n"

// psrAssertNoReversal is the acceptance criterion, stated exactly: after a
// successful landing, committing in the protected checkout must not record
// anything — in particular it must not revert the landing. `git diff --cached
// HEAD` is precisely what a plain `git commit` would capture, so it must be
// empty.
func psrAssertNoReversal(t *testing.T, root string) {
	t.Helper()
	staged := git(t, root, "diff", "--cached", "--stat", "HEAD")
	if strings.TrimSpace(staged) != "" {
		t.Fatalf("SUCCESSFUL landing left a staged reversal in the protected checkout;\na plain `git commit` here would revert the landed work:\n%s\nfull status:\n%s",
			staged, git(t, root, "status", "--porcelain", "--untracked-files=all"))
	}
}

// TestPsrSuccessfulLandingLeavesNoStagedReversalWithPermanentlyDirtyShims is
// the headline reproduction, driven through the real worker path (Store.Process
// → Worker.finalize → ProtectedFinalizer), not syncProtectedCheckout in
// isolation. The landing both MODIFIES a tracked file and ADDS a brand-new one,
// so a leftover pre-landing tree surfaces as a staged modification-reversal AND
// a staged deletion of the added file — both shapes observed in production.
func TestPsrSuccessfulLandingLeavesNoStagedReversalWithPermanentlyDirtyShims(t *testing.T) {
	root := protectedQueueRepo(t)
	psrCommitShims(t, root)
	base := git(t, root, "rev-parse", "HEAD")

	if err := os.WriteFile(filepath.Join(root, "base.txt"), []byte("base CHANGED BY LANDING\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "added-by-landing.txt"), []byte("brand new file\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	git(t, root, "add", "base.txt", "added-by-landing.txt")
	git(t, root, "commit", "-m", "landing: modify a tracked file and add a new one")
	sha := git(t, root, "rev-parse", "HEAD")
	git(t, root, "branch", "agent/candidate", sha)
	git(t, root, "reset", "--hard", base)

	// The permanent, uncapturable dirt that makes this bug fire.
	psrDirtyShims(t, root)

	store := Store{ProjectRoot: root}
	if _, err := store.Submit(Submit{Branch: "agent/candidate", SHA: sha, Receipt: persistedReceipt(t, root, sha)}); err != nil {
		t.Fatal(err)
	}
	state, err := store.Process(context.Background(), ProcessDeps{
		Integration: ProtectedIntegration{ProjectRoot: root, TargetRef: "main"},
		Gate:        ShellGate{Command: "git diff --check"},
		Finalizer:   ProtectedFinalizer{ProjectRoot: root, TargetRef: "main"},
	})
	if err != nil {
		t.Fatal(err)
	}
	c := state.Candidates[0]
	if c.phase() != Landed {
		t.Fatalf("candidate did not land: phase=%s log=%q", c.phase(), c.FinalizationLog)
	}
	if got := git(t, root, "rev-parse", "main"); got != sha {
		t.Fatalf("main=%s want %s", got, sha)
	}
	if strings.Contains(c.FinalizationLog, "checkout sync failed") {
		t.Fatalf("checkout sync was refused on a landing it should have applied: %q", c.FinalizationLog)
	}

	// THE acceptance criterion.
	psrAssertNoReversal(t, root)

	if head := git(t, root, "rev-parse", "HEAD"); head != sha {
		t.Fatalf("checkout HEAD=%s not synced to the new tip %s", head, sha)
	}
	// The landed content is really in the worktree, not just in the ref.
	got, err := os.ReadFile(filepath.Join(root, "base.txt"))
	if err != nil || string(got) != "base CHANGED BY LANDING\n" {
		t.Fatalf("worktree still holds pre-landing content for base.txt: %q err=%v", got, err)
	}
	if _, err := os.Stat(filepath.Join(root, "added-by-landing.txt")); err != nil {
		t.Fatalf("file added by the landing is missing from the worktree: %v", err)
	}

	// The excluded-root WIP that PreserveWIP declined to capture — and which
	// therefore has NO preserved-branch copy to recover from — must survive.
	// Fixing the reversal by hard-resetting over it would just trade one
	// data-loss bug for a worse one.
	for _, name := range []string{"claude", "codex"} {
		shim, err := os.ReadFile(filepath.Join(root, ".kitsoki", "bin", name))
		if err != nil || string(shim) != psrRegeneratedShim {
			t.Fatalf("uncaptured excluded-root WIP .kitsoki/bin/%s was destroyed by the sync: %q err=%v", name, shim, err)
		}
	}
	// Nothing dirty except that deliberately-untouched shim dirt.
	status := git(t, root, "status", "--porcelain", "--untracked-files=all", "--", ".", ":(exclude).capsules")
	for _, line := range strings.Split(strings.TrimSpace(status), "\n") {
		if line = strings.TrimSpace(line); line == "" {
			continue
		}
		if !strings.Contains(line, ".kitsoki/bin/") {
			t.Fatalf("unexpected dirt in the protected checkout after landing: %q (full status: %q)", line, status)
		}
	}
}

func TestPsrReadOnlyDeletedWIPSelfHealsBeforeCASAndRestoresProtection(t *testing.T) {
	root := protectedQueueRepo(t)
	locked := filepath.Join(root, "locked")
	if err := os.MkdirAll(locked, 0o755); err != nil {
		t.Fatal(err)
	}
	dirtyPath := filepath.Join(locked, "operator.txt")
	if err := os.WriteFile(dirtyPath, []byte("operator work\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	git(t, root, "add", "locked/operator.txt")
	git(t, root, "commit", "-m", "operator fixture")
	base := git(t, root, "rev-parse", "HEAD")

	if err := os.WriteFile(filepath.Join(root, "base.txt"), []byte("candidate changed base\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "candidate.txt"), []byte("candidate\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	git(t, root, "add", "base.txt", "candidate.txt")
	git(t, root, "commit", "-m", "candidate")
	sha := git(t, root, "rev-parse", "HEAD")
	git(t, root, "branch", "agent/read-only-restore", sha)
	git(t, root, "reset", "--hard", base)

	if err := os.Remove(dirtyPath); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(locked, 0o555); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(filepath.Join(root, "base.txt"), 0o444); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(root, 0o555); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() {
		_ = os.Chmod(root, 0o755)
		_ = os.Chmod(locked, 0o755)
		_ = os.Chmod(filepath.Join(root, "base.txt"), 0o644)
	})
	store := Store{ProjectRoot: root}
	submitted, err := store.Submit(Submit{
		Branch: "agent/read-only-restore", SHA: sha,
		Receipt: persistedReceipt(t, root, sha), TargetRef: "main",
	})
	if err != nil {
		t.Fatal(err)
	}
	state, err := store.Process(context.Background(), ProcessDeps{
		Integration: ProtectedIntegration{ProjectRoot: root, TargetRef: "main"},
		Gate:        ShellGate{Command: "git diff --check"},
		Finalizer:   ProtectedFinalizer{ProjectRoot: root, TargetRef: "main"},
		TargetRef:   "main",
		GateVersion: "full:git diff --check",
	})
	if err != nil {
		t.Fatal(err)
	}
	candidate := candidateByID(t, state, submitted.ID)
	if candidate.phase() != Landed {
		t.Fatalf("candidate did not land after scoped protection recovery: %#v", candidate)
	}
	if got := git(t, root, "rev-parse", "main"); got != sha {
		t.Fatalf("protected CAS result=%s want=%s", got, sha)
	}
	if staged := git(t, root, "diff", "--cached", "--stat", "HEAD"); strings.TrimSpace(staged) != "" {
		t.Fatalf("successful landing left a staged reversal: %s", staged)
	}
	if status := git(t, root, "status", "--porcelain=v1", "--untracked-files=all"); strings.TrimSpace(status) != "" {
		t.Fatalf("protected checkout did not clean before CAS: %s", status)
	}
	info, err := os.Stat(locked)
	if err != nil {
		t.Fatal(err)
	}
	if got := info.Mode().Perm(); got != 0o555 {
		t.Fatalf("protected directory mode=%#o want 0555", got)
	}
	rootInfo, err := os.Stat(root)
	if err != nil {
		t.Fatal(err)
	}
	if rootInfo.Mode().Perm() != 0o555 {
		t.Fatalf("protected root mode=%v", rootInfo.Mode())
	}
	baseInfo, err := os.Stat(filepath.Join(root, "base.txt"))
	if err != nil {
		t.Fatal(err)
	}
	if baseInfo.Mode().Perm() != 0o444 {
		t.Fatalf("protected file mode=%v", baseInfo.Mode())
	}
	branches := git(t, root, "for-each-ref", "--format=%(refname)", "refs/heads/queue/preserved-wip/")
	if strings.TrimSpace(branches) == "" {
		t.Fatal("landing did not retain a preserved-WIP recovery branch")
	}
	branch := strings.TrimSpace(strings.Split(branches, "\n")[0])
	diff := git(t, root, "diff", "--name-status", base, branch)
	if !strings.Contains(diff, "D\tlocked/operator.txt") {
		t.Fatalf("preserved branch lost operator deletion intent: %s", diff)
	}
	if got, err := os.ReadFile(dirtyPath); err != nil || string(got) != "operator work\n" {
		t.Fatalf("protected checkout did not restore tracked file before CAS: %q err=%v", got, err)
	}
}

func TestPsrUnchangedPendingProjectionSelfHealsBeforeNextCAS(t *testing.T) {
	root := protectedQueueRepo(t)
	locked := filepath.Join(root, "locked")
	if err := os.MkdirAll(locked, 0o755); err != nil {
		t.Fatal(err)
	}
	dirtyPath := filepath.Join(locked, "operator.txt")
	if err := os.WriteFile(dirtyPath, []byte("operator work\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	git(t, root, "add", "locked/operator.txt")
	git(t, root, "commit", "-m", "operator fixture")
	base := git(t, root, "rev-parse", "HEAD")

	if err := os.WriteFile(filepath.Join(root, "first.txt"), []byte("first\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	git(t, root, "add", "first.txt")
	git(t, root, "commit", "-m", "first landing")
	firstSHA := git(t, root, "rev-parse", "HEAD")
	if err := os.WriteFile(filepath.Join(root, "second.txt"), []byte("second\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	git(t, root, "add", "second.txt")
	git(t, root, "commit", "-m", "second landing")
	secondSHA := git(t, root, "rev-parse", "HEAD")
	git(t, root, "branch", "agent/second", secondSHA)
	git(t, root, "reset", "--hard", base)

	if err := os.Remove(dirtyPath); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(locked, 0o555); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(locked, 0o755) })
	git(t, root, "update-ref", "refs/heads/main", firstSHA, base)
	finalizer := ProtectedFinalizer{ProjectRoot: root, TargetRef: "main"}
	if err := finalizer.writeProjection(context.Background(), "main", firstSHA, "queue/preserved-wip/incident"); err != nil {
		t.Fatal(err)
	}

	store := Store{ProjectRoot: root}
	submitted, err := store.Submit(Submit{
		Branch: "agent/second", SHA: secondSHA,
		Receipt: persistedReceipt(t, root, secondSHA), TargetRef: "main",
	})
	if err != nil {
		t.Fatal(err)
	}
	state, err := store.Process(context.Background(), ProcessDeps{
		Integration: ProtectedIntegration{ProjectRoot: root, TargetRef: "main"},
		Gate:        ShellGate{Command: "git diff --check"},
		Finalizer:   finalizer,
		TargetRef:   "main",
		GateVersion: "full:git diff --check",
	})
	if err != nil {
		t.Fatal(err)
	}
	candidate := candidateByID(t, state, submitted.ID)
	if candidate.phase() != Landed || git(t, root, "rev-parse", "main") != secondSHA {
		t.Fatalf("pending projection did not self-heal into one landing: %#v", candidate)
	}
	if status := git(t, root, "status", "--porcelain=v1", "--untracked-files=all"); strings.TrimSpace(status) != "" {
		t.Fatalf("projection recovery left staged reversal or WIP: %s", status)
	}
	info, err := os.Stat(locked)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o555 {
		t.Fatalf("projection recovery changed protected mode: mode=%v", info.Mode())
	}
	if path, err := finalizer.projectionPath("main"); err != nil {
		t.Fatal(err)
	} else if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("recovered projection was not cleared: %v", err)
	}
}

func TestPsrExcludedTrackedReversalBlocksUnrelatedNextCAS(t *testing.T) {
	root := protectedQueueRepo(t)
	psrCommitShims(t, root)
	base := git(t, root, "rev-parse", "HEAD")

	claudeShim := filepath.Join(root, ".kitsoki", "bin", "claude")
	if err := os.WriteFile(claudeShim, []byte("#!/bin/sh\n# shim changed by first landing\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	git(t, root, "add", "-f", ".kitsoki/bin/claude")
	git(t, root, "commit", "-m", "first landing changes tracked excluded shim")
	firstSHA := git(t, root, "rev-parse", "HEAD")
	if err := os.WriteFile(filepath.Join(root, "unrelated-second.txt"), []byte("second\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	git(t, root, "add", "unrelated-second.txt")
	git(t, root, "commit", "-m", "second unrelated landing")
	secondSHA := git(t, root, "rev-parse", "HEAD")
	git(t, root, "branch", "agent/unrelated-second", secondSHA)
	git(t, root, "reset", "--hard", base)

	// Model the first CAS winning while checkout sync crashed: HEAD now names
	// firstSHA, but the index/worktree still describe base. Because .kitsoki is
	// excluded from WIP capture, the resulting staged shim reversal cannot be
	// silently cleared by the next unrelated candidate.
	git(t, root, "update-ref", "refs/heads/main", firstSHA, base)
	finalizer := ProtectedFinalizer{ProjectRoot: root, TargetRef: "main"}
	if err := finalizer.writeProjection(context.Background(), "main", firstSHA, "queue/preserved-wip/first-landing"); err != nil {
		t.Fatal(err)
	}
	if staged := git(t, root, "diff", "--cached", "--name-only", "HEAD"); !strings.Contains(staged, ".kitsoki/bin/claude") {
		t.Fatalf("fixture did not create excluded tracked reversal: %q", staged)
	}

	store := Store{ProjectRoot: root}
	submitted, err := store.Submit(Submit{
		Branch: "agent/unrelated-second", SHA: secondSHA,
		Receipt: persistedReceipt(t, root, secondSHA), TargetRef: "main",
	})
	if err != nil {
		t.Fatal(err)
	}
	state, err := store.Process(context.Background(), ProcessDeps{
		Integration: ProtectedIntegration{ProjectRoot: root, TargetRef: "main"},
		Gate:        ShellGate{Command: "git diff --check"},
		Finalizer:   finalizer,
		TargetRef:   "main",
		GateVersion: "full:git diff --check",
	})
	if err != nil {
		t.Fatal(err)
	}
	candidate := candidateByID(t, state, submitted.ID)
	if candidate.phase() != NeedsInput || candidate.RetryReason != "protected_checkout_overlap" {
		t.Fatalf("unrelated candidate was not parked immediately on excluded staged reversal: %#v", candidate)
	}
	if got := git(t, root, "rev-parse", "main"); got != firstSHA {
		t.Fatalf("second CAS moved main=%s want unchanged %s", got, firstSHA)
	}
	if staged := git(t, root, "diff", "--cached", "--name-only", "HEAD"); !strings.Contains(staged, ".kitsoki/bin/claude") {
		t.Fatalf("excluded reversal was silently cleared: %q", staged)
	}
	projectionPath, err := finalizer.projectionPath("main")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(projectionPath); err != nil {
		t.Fatalf("pending projection recovery evidence was lost: %v", err)
	}
	if !strings.Contains(candidate.Failure, "staged state after recovery") {
		t.Fatalf("candidate failure does not explain blocked projection recovery: %q", candidate.Failure)
	}
}

func TestPsrStagingCASIgnoresDifferentCheckedOutMainTree(t *testing.T) {
	root := protectedQueueRepo(t)
	base := git(t, root, "rev-parse", "main")
	git(t, root, "update-ref", "refs/heads/staging/local", base)

	if err := os.WriteFile(filepath.Join(root, "shared.txt"), []byte("main checkout\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	git(t, root, "add", "shared.txt")
	git(t, root, "commit", "-m", "main changes shared path")
	mainSHA := git(t, root, "rev-parse", "main")

	git(t, root, "checkout", "-b", "agent/staging-shared", base)
	if err := os.WriteFile(filepath.Join(root, "shared.txt"), []byte("staging candidate\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	git(t, root, "add", "shared.txt")
	git(t, root, "commit", "-m", "staging changes same shared path")
	candidateSHA := git(t, root, "rev-parse", "HEAD")
	git(t, root, "checkout", "main")
	if err := os.WriteFile(filepath.Join(root, "shared.txt"), []byte("dirty operator main checkout\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "operator-untracked.txt"), []byte("untracked operator work\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	statusBefore := git(t, root, "status", "--porcelain=v1", "--untracked-files=all", "--", ".", ":(exclude).capsules", ":(exclude).capsules/**")
	indexBefore := git(t, root, "write-tree")
	preservedBefore := git(t, root, "for-each-ref", "--format=%(refname)", "refs/heads/queue/preserved-wip/")

	store := Store{ProjectRoot: root}
	submitted, err := store.Submit(Submit{
		Branch: "agent/staging-shared", SHA: candidateSHA,
		Receipt: persistedReceipt(t, root, candidateSHA), TargetRef: "staging/local",
	})
	if err != nil {
		t.Fatal(err)
	}
	state, err := store.Process(context.Background(), ProcessDeps{
		Integration: ProtectedIntegration{ProjectRoot: root, TargetRef: "staging/local"},
		Gate:        ShellGate{Command: "git diff --check"},
		Finalizer:   ProtectedFinalizer{ProjectRoot: root, TargetRef: "staging/local"},
		TargetRef:   "staging/local",
		GateVersion: "change:git diff --check",
	})
	if err != nil {
		t.Fatal(err)
	}
	candidate := candidateByID(t, state, submitted.ID)
	if candidate.phase() != Landed || git(t, root, "rev-parse", "staging/local") != candidateSHA {
		t.Fatalf("staging candidate did not land while main was checked out: %#v", candidate)
	}
	if got := git(t, root, "rev-parse", "main"); got != mainSHA {
		t.Fatalf("staging CAS moved main=%s want=%s", got, mainSHA)
	}
	if got := git(t, root, "rev-parse", "HEAD"); got != mainSHA {
		t.Fatalf("staging CAS moved checked-out HEAD=%s want=%s", got, mainSHA)
	}
	if got, err := os.ReadFile(filepath.Join(root, "shared.txt")); err != nil || string(got) != "dirty operator main checkout\n" {
		t.Fatalf("staging CAS touched main worktree: %q err=%v", got, err)
	}
	if got, err := os.ReadFile(filepath.Join(root, "operator-untracked.txt")); err != nil || string(got) != "untracked operator work\n" {
		t.Fatalf("staging CAS touched untracked main WIP: %q err=%v", got, err)
	}
	if statusAfter := git(t, root, "status", "--porcelain=v1", "--untracked-files=all", "--", ".", ":(exclude).capsules", ":(exclude).capsules/**"); statusAfter != statusBefore {
		t.Fatalf("staging CAS changed main status:\nbefore=%q\nafter=%q", statusBefore, statusAfter)
	}
	if indexAfter := git(t, root, "write-tree"); indexAfter != indexBefore {
		t.Fatalf("staging CAS changed main index: before=%s after=%s", indexBefore, indexAfter)
	}
	if preservedAfter := git(t, root, "for-each-ref", "--format=%(refname)", "refs/heads/queue/preserved-wip/"); preservedAfter != preservedBefore {
		t.Fatalf("staging CAS preserved unrelated main WIP: before=%q after=%q", preservedBefore, preservedAfter)
	}
	finalizer := ProtectedFinalizer{ProjectRoot: root, TargetRef: "staging/local"}
	if projection, err := finalizer.projectionPath("staging/local"); err != nil {
		t.Fatal(err)
	} else if _, err := os.Stat(projection); !os.IsNotExist(err) {
		t.Fatalf("staging CAS created checkout projection while main was checked out: %v", err)
	}
}

// TestPsrSuccessfulLandingThatDeletesAFileLeavesNoReversal covers the third
// shape of the reversal: when the landing DELETES a tracked file, a refused
// sync leaves the deleted file present on disk and staged as an addition, so
// committing re-adds content the landing removed.
func TestPsrSuccessfulLandingThatDeletesAFileLeavesNoReversal(t *testing.T) {
	root := protectedQueueRepo(t)
	psrCommitShims(t, root)
	commit(t, root, "doomed.txt", "delete me in the landing\n", "add a file the landing will delete")
	base := git(t, root, "rev-parse", "HEAD")

	git(t, root, "rm", "-q", "doomed.txt")
	git(t, root, "commit", "-m", "landing: delete a tracked file")
	sha := git(t, root, "rev-parse", "HEAD")
	git(t, root, "branch", "agent/candidate", sha)
	git(t, root, "reset", "--hard", base)

	psrDirtyShims(t, root)

	store := Store{ProjectRoot: root}
	if _, err := store.Submit(Submit{Branch: "agent/candidate", SHA: sha, Receipt: persistedReceipt(t, root, sha)}); err != nil {
		t.Fatal(err)
	}
	state, err := store.Process(context.Background(), ProcessDeps{
		Integration: ProtectedIntegration{ProjectRoot: root, TargetRef: "main"},
		Gate:        ShellGate{Command: "git diff --check"},
		Finalizer:   ProtectedFinalizer{ProjectRoot: root, TargetRef: "main"},
	})
	if err != nil {
		t.Fatal(err)
	}
	if c := state.Candidates[0]; c.phase() != Landed {
		t.Fatalf("candidate did not land: phase=%s log=%q", c.phase(), c.FinalizationLog)
	}
	psrAssertNoReversal(t, root)
	if _, err := os.Stat(filepath.Join(root, "doomed.txt")); !os.IsNotExist(err) {
		t.Fatalf("file deleted by the landing is still present in the worktree (err=%v)", err)
	}
}

// TestPsrSyncAdvancesLandedPathsDespitePermanentExcludedRootDirt pins the
// eligibility fix directly at the unit boundary: dirt under an excluded root
// must not make the sync refuse, because a path the landing never touched
// cannot need syncing.
func TestPsrSyncAdvancesLandedPathsDespitePermanentExcludedRootDirt(t *testing.T) {
	dir := wipRepo(t)
	if err := os.MkdirAll(filepath.Join(dir, ".kitsoki", "bin"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".kitsoki", "bin", "claude"), []byte("shim v1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	git(t, dir, "add", "-f", ".kitsoki/bin/claude")
	git(t, dir, "commit", "-m", "shim")
	oldSHA := git(t, dir, "rev-parse", "HEAD")
	// Permanently dirty excluded-root path: never captured, never cleaned.
	if err := os.WriteFile(filepath.Join(dir, ".kitsoki", "bin", "claude"), []byte("shim REGENERATED\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// The landing advances a path that has nothing to do with .kitsoki.
	newSHA := psrAdvanceRef(t, dir, oldSHA, map[string]string{"tracked.txt": "v2"})

	if _, err := syncProtectedCheckout(context.Background(), dir, "refs/heads/main", oldSHA); err != nil {
		t.Fatalf("excluded-root dirt must not block the sync, got err=%v", err)
	}
	if got := git(t, dir, "rev-parse", "HEAD"); got != newSHA {
		t.Fatalf("HEAD=%s want %s", got, newSHA)
	}
	psrAssertNoReversal(t, dir)
	shim, err := os.ReadFile(filepath.Join(dir, ".kitsoki", "bin", "claude"))
	if err != nil || string(shim) != "shim REGENERATED\n" {
		t.Fatalf("excluded-root WIP destroyed by the sync: %q err=%v", shim, err)
	}
}

// TestPsrSyncRefusesLoudlyAndNamesAPathTheLandingAndOperatorBothChanged covers
// the genuine collision. When the landing changed a path the operator also
// holds dirty there is no defensible silent winner: overwriting loses the local
// edit (which, under an excluded root, has no preserved-branch copy), and
// skipping leaves a reversal. It must fail loudly and NAME the path.
func TestPsrSyncRefusesLoudlyAndNamesAPathTheLandingAndOperatorBothChanged(t *testing.T) {
	dir := wipRepo(t)
	if err := os.MkdirAll(filepath.Join(dir, ".kitsoki", "bin"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, ".kitsoki", "bin", "claude"), []byte("shim v1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	git(t, dir, "add", "-f", ".kitsoki/bin/claude")
	git(t, dir, "commit", "-m", "shim")
	oldSHA := git(t, dir, "rev-parse", "HEAD")
	if err := os.WriteFile(filepath.Join(dir, ".kitsoki", "bin", "claude"), []byte("operator local edit\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	// This time the landing changes that very path too.
	psrAdvanceRef(t, dir, oldSHA, map[string]string{".kitsoki/bin/claude": "shim v2 from the landing\n", "tracked.txt": "v2"})

	_, err := syncProtectedCheckout(context.Background(), dir, "refs/heads/main", oldSHA)
	if err == nil {
		t.Fatal("expected a loud refusal when the landing and the operator both changed a path")
	}
	var conflict *ProtectedSyncConflictError
	if !asProtectedSyncConflict(err, &conflict) {
		t.Fatalf("err=%T %v, want *ProtectedSyncConflictError", err, err)
	}
	if !strings.Contains(err.Error(), ".kitsoki/bin/claude") {
		t.Fatalf("refusal does not name the conflicting path: %v", err)
	}
	got, readErr := os.ReadFile(filepath.Join(dir, ".kitsoki", "bin", "claude"))
	if readErr != nil || string(got) != "operator local edit\n" {
		t.Fatalf("refusal must leave the operator's content untouched: %q err=%v", got, readErr)
	}
}

// TestPsrSyncRefusesWhenTheLandingAddedAFileTheOperatorAlreadyCreated covers
// the added-file form of the same collision: an untracked file sitting exactly
// where the landing adds one has no preserved-branch copy, so it must never be
// silently overwritten.
func TestPsrSyncRefusesWhenTheLandingAddedAFileTheOperatorAlreadyCreated(t *testing.T) {
	dir := wipRepo(t)
	oldSHA := git(t, dir, "rev-parse", "HEAD")
	if err := os.WriteFile(filepath.Join(dir, "collides.txt"), []byte("operator wrote this first\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	psrAdvanceRef(t, dir, oldSHA, map[string]string{"tracked.txt": "v1", "collides.txt": "added by the landing\n"})

	_, err := syncProtectedCheckout(context.Background(), dir, "refs/heads/main", oldSHA)
	if err == nil || !strings.Contains(err.Error(), "collides.txt") {
		t.Fatalf("err=%v, want a refusal naming collides.txt", err)
	}
	got, readErr := os.ReadFile(filepath.Join(dir, "collides.txt"))
	if readErr != nil || string(got) != "operator wrote this first\n" {
		t.Fatalf("refusal must leave the operator's untracked file untouched: %q err=%v", got, readErr)
	}
}

// TestPsrSyncRefusesWithoutAPreFinalizationTip pins the degenerate input:
// without the pre-finalization tip there is no way to tell stale pre-landing
// content apart from genuine local WIP, so no mutation can be proven safe.
func TestPsrSyncRefusesWithoutAPreFinalizationTip(t *testing.T) {
	dir := wipRepo(t)
	if err := os.WriteFile(filepath.Join(dir, "tracked.txt"), []byte("local\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	_, err := syncProtectedCheckout(context.Background(), dir, "refs/heads/main", "  ")
	if err == nil || !strings.Contains(err.Error(), "without the pre-finalization tip") {
		t.Fatalf("err=%v, want a refusal naming the missing pre-finalization tip", err)
	}
	got, readErr := os.ReadFile(filepath.Join(dir, "tracked.txt"))
	if readErr != nil || string(got) != "local\n" {
		t.Fatalf("refusal must not touch the worktree: %q err=%v", got, readErr)
	}
}

// psrAdvanceRef writes contents as a new commit on top of oldSHA and moves
// refs/heads/main to it entirely through plumbing against a scratch index, so
// the ref advances without the real index or the working tree ever being
// touched — the exact post-CAS precondition syncProtectedCheckout is designed
// for. Paths in oldSHA but absent from contents are carried forward unchanged.
func psrAdvanceRef(t *testing.T, dir, oldSHA string, contents map[string]string) string {
	t.Helper()
	idx := filepath.Join(t.TempDir(), "psr-index")
	env := append(os.Environ(), "GIT_INDEX_FILE="+idx)
	psrGitEnv(t, dir, env, "read-tree", oldSHA)
	for path, text := range contents {
		blob := psrHashObject(t, dir, env, text)
		psrGitEnv(t, dir, env, "update-index", "--add", "--cacheinfo", "100644,"+blob+","+path)
	}
	tree := psrGitEnv(t, dir, env, "write-tree")
	newSHA := git(t, dir, "commit-tree", tree, "-p", oldSHA, "-m", "landing")
	git(t, dir, "update-ref", "refs/heads/main", newSHA)
	return newSHA
}

func psrGitEnv(t *testing.T, dir string, env []string, args ...string) string {
	t.Helper()
	cmd := exec.Command("git", args...)
	cmd.Dir = dir
	cmd.Env = env
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git %s: %v\n%s", strings.Join(args, " "), err, out)
	}
	return strings.TrimSpace(string(out))
}

func psrHashObject(t *testing.T, dir string, env []string, text string) string {
	t.Helper()
	cmd := exec.Command("git", "hash-object", "-w", "--stdin")
	cmd.Dir = dir
	cmd.Env = env
	cmd.Stdin = strings.NewReader(text)
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("git hash-object: %v\n%s", err, out)
	}
	return strings.TrimSpace(string(out))
}

func asProtectedSyncConflict(err error, target **ProtectedSyncConflictError) bool {
	return errors.As(err, target)
}
