/**
 * Build-time loader for the extension library index generated by
 * `kitsoki docs index`. The product site reads this from .vitepress/gen instead
 * of maintaining a parallel catalog by hand.
 */
import * as fs from "fs";
import * as path from "path";
import { repoRoot, siteDir } from "./features.js";

const genIndex = path.join(siteDir, ".vitepress", "gen", "extensions-index.json");

export interface ExtensionDoc {
  id: string;
  owner: string;
  title: string;
  path?: string;
  generated_from?: string;
  kind?: string;
  publish: "true" | "false" | "summary" | "full";
}

export interface ExtensionPackage {
  id: string;
  slug: string;
  kind: string;
  title: string;
  summary: string;
  version?: string;
  path: string;
  provides: string[];
  requires: string[];
  conformance: string[];
  docs: string[];
  publishedDocs: ExtensionDoc[];
  stories: ExtensionStory[];
}

export interface ExtensionStory {
  id: string;
  slug: string;
  package_id?: string;
  packageSlug?: string | null;
  title: string;
  version?: string;
  path: string;
  world_keys: string[];
  intents: string[];
  states: string[];
  agents: string[];
  agent_plugins: string[];
  host_interfaces: string[];
  exports: string[];
  exits: string[];
  flows: string[];
}

export interface ExtensionComponent {
  id: string;
  owner: string;
  kind: string;
  path?: string;
  generated_from?: string;
}

export interface ExtensionLibraryIndex {
  schema: string;
  packages: ExtensionPackage[];
  stories: ExtensionStory[];
  components: ExtensionComponent[];
  docs: ExtensionDoc[];
}

export interface ExtensionLibrary {
  packages: ExtensionPackage[];
  stories: ExtensionStory[];
  standaloneStories: ExtensionStory[];
  components: ExtensionComponent[];
  docs: ExtensionDoc[];
  stats: {
    packages: number;
    stories: number;
    publishedDocs: number;
    hostInterfaces: number;
    agents: number;
    flows: number;
  };
}

let cache: ExtensionLibrary | null = null;

export function extensionSlug(id: string): string {
  return id
    .replace(/^@/, "")
    .replace(/^story:/, "story-")
    .replace(/[^A-Za-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase();
}

function asArray(value: unknown): string[] {
  return Array.isArray(value) ? value.map(String) : [];
}

function assertIndex(index: ExtensionLibraryIndex) {
  if (index.schema !== "kitsoki.extensions-index/v1") {
    throw new Error(`unexpected extension index schema: ${index.schema}`);
  }
  if (!Array.isArray(index.packages) || !Array.isArray(index.stories) || !Array.isArray(index.docs)) {
    throw new Error("extension index is missing packages/stories/docs arrays");
  }
}

function published(doc: ExtensionDoc): boolean {
  return doc.publish !== "false";
}

export function loadExtensionLibrary(): ExtensionLibrary {
  if (cache) return cache;
  if (!fs.existsSync(genIndex)) {
    throw new Error(
      `${path.relative(repoRoot, genIndex)} missing - run: make site-data site-stage or make site`,
    );
  }
  const raw = JSON.parse(fs.readFileSync(genIndex, "utf8")) as ExtensionLibraryIndex;
  assertIndex(raw);

  const docs = raw.docs.filter(published).sort((a, b) => a.title.localeCompare(b.title));
  const docsByID = new Map(docs.map((doc) => [doc.id, doc]));
  const packageSlugs = new Map(raw.packages.map((pkg) => [pkg.id, extensionSlug(pkg.id)]));

  const stories: ExtensionStory[] = raw.stories
    .map((story: any) => ({
      id: String(story.id),
      slug: extensionSlug(String(story.id)),
      package_id: story.package_id ? String(story.package_id) : undefined,
      packageSlug: story.package_id ? packageSlugs.get(String(story.package_id)) ?? null : null,
      title: String(story.title || story.id),
      version: story.version ? String(story.version) : undefined,
      path: String(story.path || ""),
      world_keys: asArray(story.world_keys),
      intents: asArray(story.intents),
      states: asArray(story.states),
      agents: asArray(story.agents),
      agent_plugins: asArray(story.agent_plugins),
      host_interfaces: asArray(story.host_interfaces),
      exports: asArray(story.exports),
      exits: asArray(story.exits),
      flows: asArray(story.flows),
    }))
    .sort((a, b) => a.title.localeCompare(b.title) || a.id.localeCompare(b.id));

  const storiesByPackage = new Map<string, ExtensionStory[]>();
  for (const story of stories) {
    if (!story.package_id) continue;
    const bucket = storiesByPackage.get(story.package_id) ?? [];
    bucket.push(story);
    storiesByPackage.set(story.package_id, bucket);
  }

  const packages: ExtensionPackage[] = raw.packages
    .map((pkg: any) => {
      const docIDs = asArray(pkg.docs);
      return {
        id: String(pkg.id),
        slug: extensionSlug(String(pkg.id)),
        kind: String(pkg.kind || "package"),
        title: String(pkg.title || pkg.id),
        summary: String(pkg.summary || "").trim(),
        version: pkg.version ? String(pkg.version) : undefined,
        path: String(pkg.path || ""),
        provides: asArray(pkg.provides),
        requires: asArray(pkg.requires),
        conformance: asArray(pkg.conformance),
        docs: docIDs,
        publishedDocs: docIDs.map((id) => docsByID.get(id)).filter((doc): doc is ExtensionDoc => !!doc),
        stories: storiesByPackage.get(String(pkg.id)) ?? [],
      };
    })
    .sort((a, b) => a.title.localeCompare(b.title) || a.id.localeCompare(b.id));

  const hostInterfaces = new Set<string>();
  const agents = new Set<string>();
  let flows = 0;
  for (const story of stories) {
    story.host_interfaces.forEach((x) => hostInterfaces.add(x));
    story.agents.forEach((x) => agents.add(x));
    story.agent_plugins.forEach((x) => agents.add(x));
    flows += story.flows.length;
  }

  cache = {
    packages,
    stories,
    standaloneStories: stories.filter((story) => !story.package_id),
    components: raw.components ?? [],
    docs,
    stats: {
      packages: packages.length,
      stories: stories.length,
      publishedDocs: docs.length,
      hostInterfaces: hostInterfaces.size,
      agents: agents.size,
      flows,
    },
  };
  return cache;
}

export function librarySidebar() {
  const library = loadExtensionLibrary();
  return [
    { text: "Library", link: "/library/" },
    {
      text: "Packages",
      collapsed: false,
      items: library.packages.map((pkg) => ({ text: pkg.title, link: `/library/packages/${pkg.slug}` })),
    },
    {
      text: "Standalone stories",
      collapsed: true,
      items: library.standaloneStories.slice(0, 40).map((story) => ({ text: story.title, link: `/library/stories/${story.slug}` })),
    },
  ];
}
