/**
 * tier2.ts — swarm tier 2: cassette-agent users.
 *
 * Tier 1 (tools/swarm/journey.ts) drives explicit intents only — zero free
 * text, zero routing. Tier 2 adds FREE-TEXT REALISM while staying zero-LLM:
 * the user types a real sentence, and a `--harness replay --recording ...`
 * session (an interpreter harness backed by a hand-authorable recording,
 * NOT the nil-harness `--flow` fixture tier 1 uses) routes it deterministically,
 * with a host cassette answering whatever host.* call the routed path fires.
 *
 * Fixture reuse: rather than hand-authoring a new story/recording/cassette
 * trio, this tier reuses `stories/off-ramp-demo` verbatim — it already
 * exercises exactly the `--harness replay --recording assets/recording.yaml
 * --host-cassette assets/converse-cassette.yaml` posture end-to-end (see
 * off-ramp-video.spec.ts), and its "agent off-ramp" feature is a genuine
 * free-text interaction: an off-menu QUESTION is answered in place (no state
 * change) via host.agent.converse, stubbed by the cassette. The menu itself
 * (browse/status/about) is driven by explicit intents needing no recording
 * entry at all — see `stories/off-ramp-demo/assets/recording.yaml`'s own doc
 * comment — which is exactly the affordance `scriptedMixUser.ts` uses to put
 * a tier-1-STYLE (scripted, zero free text) user on the SAME server.
 *
 * The one wrinkle: `internal/harness/replay.go`'s `ReplayHarness` matches
 * recording entries by EXACT (case-insensitive, trimmed) input text — no
 * fuzzy/embedding match — so tier 1's "prepend a unique isolation marker to
 * the free text" trick (journey.ts / isolation.ts) would silently break the
 * off-ramp's canned recording entry (the marker-bearing string would no
 * longer match ANY entry, falling through to a real, non-deterministic
 * intent-routing attempt). `buildTier2Recording` below derives a SMALL,
 * per-run recording file from the real fixture — one entry per swarm user,
 * each mapping THAT user's own marker-bearing off-menu question to the exact
 * same `clarify: true` / canned-message shape the shipped recording uses —
 * so every user's utterance still resolves deterministically AND still
 * carries a marker the trace-based isolation check (isolation.ts) can look
 * for. The host cassette needs no such per-user variant: it matches
 * `match_on: [handler]` (the call name, not its content — see
 * `stories/off-ramp-demo/assets/converse-cassette.yaml`'s doc comment), so
 * the exact same canned answer already backs every user's question.
 */
import fs from "fs";
import os from "os";
import path from "path";
import type { Page } from "@playwright/test";
import { waitForState } from "../../runstatus/tests/playwright/_helpers/server.js";
import { checkIsolation, type IsolationResult } from "../isolation.js";
import type { TaggedFinding } from "../audit.js";

export const repoRoot = path.resolve(path.dirname(new URL(import.meta.url).pathname), "../../..");
export const OFF_RAMP_STORY_DIR = path.join(repoRoot, "stories", "off-ramp-demo");
export const OFF_RAMP_RECORDING = path.join(OFF_RAMP_STORY_DIR, "assets", "recording.yaml");
export const OFF_RAMP_HOST_CASSETTE = path.join(OFF_RAMP_STORY_DIR, "assets", "converse-cassette.yaml");

/** The real fixture's off-menu question (kept verbatim so the derived
 *  recording's canned `message` stays word-for-word identical to the shipped
 *  demo — only `input` gains a per-user marker prefix). */
export const OFF_MENU_QUESTION = "why should I trust an AI with my project?";
const CANNED_CLARIFY_MESSAGE = "I don't have a menu item for that — let me just answer it.";

export function markerQuestion(marker: string): string {
  return `${marker} :: ${OFF_MENU_QUESTION}`;
}

/**
 * Writes a temp recording YAML (structurally identical to
 * `stories/off-ramp-demo/assets/recording.yaml`, just N entries instead of
 * one) mapping each of `markers`' `markerQuestion` to the same deterministic
 * clarify response the shipped fixture uses. Returns the written path.
 * Deliberately hand-rolled YAML (the shape is four scalar lines per entry)
 * rather than a dependency on a YAML-writing library tools/swarm doesn't
 * have (see tools/swarm/README.md "why no dependencies").
 */
export function buildTier2Recording(markers: string[], outDir: string): string {
  fs.mkdirSync(outDir, { recursive: true });
  const yamlEscape = (s: string): string => JSON.stringify(s); // valid YAML double-quoted scalar
  const entries = markers
    .map(
      (m) =>
        `  - state: desk\n    input: ${yamlEscape(markerQuestion(m))}\n    clarify: true\n    message: ${yamlEscape(CANNED_CLARIFY_MESSAGE)}\n`,
    )
    .join("");
  const doc = [
    "# Generated by tools/swarm/tiers/tier2.ts (buildTier2Recording) — DO NOT EDIT BY HAND.",
    "# One clarify entry per swarm user, derived from stories/off-ramp-demo/assets/recording.yaml",
    "# so each user's marker-bearing off-menu question still resolves deterministically.",
    "kind: recording",
    "app_id: off-ramp-demo",
    "app_version: 0.1.0",
    `generated_at: "${new Date().toISOString()}"`,
    'generator: "tools/swarm/tiers/tier2.ts buildTier2Recording"',
    "min_confidence: 1.00",
    "",
    "entries:",
    entries,
  ].join("\n");
  const outPath = path.join(outDir, "tier2-recording.yaml");
  fs.writeFileSync(outPath, doc);
  return outPath;
}

/** Makes a fresh scratch dir under the OS tmp root for one run's derived
 *  recording file (kept out of the repo/.artifacts tree — this is a
 *  throwaway input fixture, not a result artifact). */
export function makeTier2ScratchDir(runId: string): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), `kitsoki-swarm-tier2-${runId}-`));
}

export type RpcFn = <T>(method: string, params: Record<string, unknown>) => Promise<T>;
export type AuditFn = (page: Page, state: string) => Promise<TaggedFinding[]>;

const STEP_TIMEOUT_MS = 60000;

async function waitVisible(page: Page, testId: string, timeoutMs = STEP_TIMEOUT_MS) {
  await page.getByTestId(testId).first().waitFor({ state: "visible", timeout: timeoutMs });
}

/** Types `text` into the off-ramp story's free-text floor (NOT
 *  `composer-input` — a MENU room's free-text box is `text-floor-input`, see
 *  off-ramp-video.spec.ts's doc comment) and sends it via the native-setter +
 *  `input` event dispatch pattern every swarm driver uses (Vue v-model
 *  reliability, not a `.fill()` quirk). */
async function sendFreeText(page: Page, text: string): Promise<void> {
  const input = page.getByTestId("text-floor-input").first();
  await input.waitFor({ state: "visible", timeout: STEP_TIMEOUT_MS });
  await input.evaluate((el, value) => {
    const node = el as HTMLInputElement | HTMLTextAreaElement;
    const proto = Object.getPrototypeOf(node);
    const setter = Object.getOwnPropertyDescriptor(proto, "value")?.set;
    setter?.call(node, value);
    node.dispatchEvent(new Event("input", { bubbles: true }));
  }, text);
  await page.getByTestId("text-floor-send").first().click();
}

export interface CassetteJourneyResult {
  session_id: string;
  states_visited: string[];
  audit_findings: TaggedFinding[];
  duration_ms: number;
}

/** Phase 1 (mirrors journey.ts's openUserSession): mint + open, unthrottled
 *  so every tier-2 user is "concurrently live" alongside tier-1 users on the
 *  same server as soon as it mints. */
export async function openCassetteUserSession(opts: {
  page: Page;
  base: string;
  rpc: RpcFn;
  storyPath: string;
}): Promise<{ session_id: string }> {
  const { page, base, rpc, storyPath } = opts;
  const { session_id } = await rpc<{ session_id: string }>("runstatus.session.new", {
    story_path: storyPath,
  });
  await page.goto(`${base}/#/s/${session_id}/chat`);
  await waitVisible(page, "chat-section");
  await waitForState(page, "desk", STEP_TIMEOUT_MS);
  return { session_id };
}

/**
 * Phase 2: the free-text off-ramp journey. Sends this user's OWN
 * marker-bearing question (matched by `buildTier2Recording`'s derived
 * entry), asserts the off-ramp answered IN PLACE (no state change, menu
 * intact — the off-ramp's whole point), then proves the menu still works
 * with a real explicit-intent transition (browse -> catalogue), auditing
 * each distinct state reached exactly like tier 1.
 */
export async function driveCassetteUserJourney(opts: {
  page: Page;
  session_id: string;
  marker: string;
  audit: AuditFn;
}): Promise<CassetteJourneyResult> {
  const { page, session_id, marker, audit } = opts;
  const t0 = Date.now();
  const states: string[] = [];
  const findings: TaggedFinding[] = [];
  const visited = new Set<string>();

  async function auditOnce(state: string): Promise<void> {
    states.push(state);
    if (visited.has(state)) return;
    visited.add(state);
    findings.push(...(await audit(page, state)));
  }

  await auditOnce("desk");

  await sendFreeText(page, markerQuestion(marker));
  await waitVisible(page, "offramp-bubble");
  const bubble = page.getByTestId("offramp-bubble");
  await bubble.waitFor({ state: "visible", timeout: STEP_TIMEOUT_MS });
  const mode = await bubble.getAttribute("data-mode");
  if (mode !== "offpath") {
    throw new Error(`tier2: expected offramp-bubble data-mode="offpath", got ${JSON.stringify(mode)}`);
  }
  await waitVisible(page, "offramp-chip");
  // THE CONTRAST that proves the off-ramp didn't bounce state: still "desk",
  // menu still present.
  await waitForState(page, "desk", 5000);
  await waitVisible(page, "intent-btn-browse", 5000);
  await auditOnce("desk-offramp-answered");

  // A real explicit-intent transition, needing no recording entry at all —
  // proves this session's menu still works after the free-text detour.
  const browseBtn = page.getByTestId("intent-btn-browse").first();
  await browseBtn.waitFor({ state: "visible", timeout: STEP_TIMEOUT_MS });
  await browseBtn.click();
  await waitForState(page, "catalogue", STEP_TIMEOUT_MS);
  await auditOnce("catalogue");

  return {
    session_id,
    states_visited: states,
    audit_findings: findings,
    duration_ms: Date.now() - t0,
  };
}

/** Same trace-based ground truth as tier 1's `assertIsolated` (isolation.ts)
 *  — re-exported thinly here so tier-2 call sites don't need to reach into
 *  journey.ts (which is tier-1-specific: PRD story states, composer-select
 *  intents). */
export async function assertCassetteIsolated(
  rpc: RpcFn,
  session_id: string,
  otherMarkers: string[],
): Promise<IsolationResult> {
  const trace = await rpc<unknown>("runstatus.session.trace", { session_id });
  return checkIsolation(JSON.stringify(trace), otherMarkers);
}
