import { type TourStep } from "./types.js";

export type { TourStep };

export const META_IMPROVE_TOUR_STEPS: readonly TourStep[] = [
  {
    id: "mi-intro-home",
    route: "home",
    title: "Run improvement closes the loop",
    body: "This tour shows a complete session, the end-of-run improve reminder, and the real story.improve meta mode producing an introspection report.",
    placement: "center",
    kind: "explain",
    advance: "next",
    waitForTarget: "home-view",
    dwellMs: 4800,
  },
  {
    id: "mi-story-card",
    route: "home",
    target: "story-card",
    title: "A deterministic story run",
    body: "The demo uses the Cloak story with a no-LLM flow fixture, so the run is short, repeatable, and free to record.",
    placement: "right",
    kind: "explain",
    advance: "next",
    waitForTarget: "story-card",
    dwellMs: 4200,
  },
  {
    id: "mi-new-session",
    route: "home",
    target: "new-session-btn",
    title: "Start the session",
    body: "Open a fresh drive view. We will advance the story just far enough to reach a terminal state.",
    placement: "right",
    kind: "explain",
    advance: "next",
    waitForTarget: "new-session-btn",
    dwellMs: 3600,
  },
  {
    id: "mi-start-run",
    route: "interactive",
    target: "current-state",
    title: "Kick off the run",
    body: "The first frame shows the story output, current room, and available action before we move.",
    placement: "top",
    kind: "explain",
    advance: "next",
    waitForTarget: "current-state",
    dwellMs: 3600,
  },
  {
    id: "mi-mid-run",
    route: "interactive",
    target: "current-state",
    title: "A brief middle beat",
    body: "The run moves through a couple of deterministic turns. This keeps the demo focused on the improvement loop.",
    placement: "bottom",
    kind: "explain",
    advance: "next",
    waitForTarget: "current-state",
    dwellMs: 3800,
  },
  {
    id: "mi-complete-run",
    route: "interactive",
    target: "intent-btn-read_message",
    title: "Complete the session",
    body: "Reading the message lands in the terminal state. This is where kitsoki should make improvement the obvious next step.",
    placement: "top",
    kind: "explain",
    advance: "next",
    waitForTarget: "intent-btn-read_message",
    dwellMs: 4200,
  },
  {
    id: "mi-reminder",
    route: "interactive",
    target: "improve-prompt",
    title: "The reminder appears at completion",
    body: "At the end of the session, kitsoki recommends reviewing the run for false starts, wasted tool calls, prompt/tool changes, scripts, permission cleanup, and no-LLM regression coverage.",
    placement: "top",
    kind: "explain",
    advance: "next",
    waitForTarget: "improve-prompt",
    dwellMs: 5600,
  },
  {
    id: "mi-auto-run",
    route: "interactive",
    target: "improve-auto-toggle",
    title: "Auto-run is one checkbox away",
    body: "The same affordance can auto-run improve for future completions. For this demo we will keep it manual and click Run improve now.",
    placement: "top",
    kind: "explain",
    advance: "next",
    waitForTarget: "improve-auto-toggle",
    dwellMs: 4600,
  },
  {
    id: "mi-evidence-report",
    route: "interactive",
    target: "improve-report-toggle",
    title: "Evidence filing is built in",
    body: "The same affordance can file a durable introspection report with trace, HAR, replay, console, and posting metadata. Users can force a local artifact or use the configured ticket sink.",
    placement: "top",
    kind: "explain",
    advance: "next",
    waitForTarget: "improve-report-toggle",
    dwellMs: 5200,
  },
  {
    id: "mi-run-improve",
    route: "interactive",
    target: "improve-run",
    title: "Run improve now",
    body: "This button opens Meta in story.improve and sends the standard completed-session improvement prompt.",
    placement: "top",
    kind: "explain",
    advance: "next",
    waitForTarget: "improve-run",
    dwellMs: 4200,
  },
  {
    id: "mi-improve-stream",
    route: "interactive",
    target: "meta-row-streaming",
    title: "The actual story.improve turn runs",
    body: "The meta overlay streams a real story.improve turn through the same Meta infrastructure users get, backed here by the deterministic no-LLM stub.",
    placement: "right",
    kind: "explain",
    advance: "next",
    waitForTarget: "meta-row-streaming",
    dwellMs: 4800,
  },
  {
    id: "mi-report-ready",
    route: "interactive",
    target: "meta-row-agent",
    title: "The introspection report is ready",
    body: "The report identifies the durable improvement loop: keep the reminder visible, keep improve read-only, and cover completion to improve with no-LLM evidence.",
    placement: "right",
    kind: "explain",
    advance: "next",
    waitForTarget: "meta-row-agent",
    dwellMs: 5600,
  },
  {
    id: "mi-artifacts-filed",
    route: "interactive",
    target: "improve-report-status",
    title: "Artifacts are ready for review",
    body: "After the meta report finishes, kitsoki files the evidence bundle and shows the destination, report path, and sidecar files.",
    placement: "top",
    kind: "explain",
    advance: "next",
    waitForTarget: "improve-report-status",
    dwellMs: 5600,
  },
];
